rootProject.name = 'fraud-agentic-ai-showcase'

include 'components:domains'
include ':applications:fraud-app'
include ':applications:integration:sinks:vector-sink'
include ':applications:integration:processors:remove-by-gf-search-processor'
include ':applications:integration:processors:alert-ai-agent-processor'

