spring.application.name=fraud-app
server.port=5010

#GemFire
spring.data.gemfire.pool.locators=localhost[10334]
spring.ai.vectorstore.gemfire.host=localhost
spring.ai.vectorstore.gemfire.port=7080
spring.ai.vectorstore.gemfire.initialize-schema=true

## Ollama
#spring.ai.ollama.chat.options.model=gemma
#spring.ai.ollama.chat.options.model=llama3
#spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.model=gpt-oss:20b
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=WHEN_MISSING


# MCP Client

spring.ai.mcp.client.streamable-http.connections.activities.url=http://localhost:7901
spring.ai.mcp.client.streamable-http.connections.activities.endpoint=/api/mcp